### PR TITLE
Implement a video title section on the homepage.

### LINKED ISSUE #101: Video Modal on the homepage of showreel

### LINKED ISSUE #102: Video in the background of the homepage
On loop

### PR DESCRIPTION
**Pull request by Jason2605**
Currently the homepage has a static image for the title section. This PR changes this image to a short video. This PR also embeds the showreel image into the homepage as well instead of opening a new tab linking to Vimeo.

Closes #101 
Closes #102

### CODE REVIEW

**Review by ianoshorty — CHANGES_REQUESTED** [review]
The video has problems at various screen sizes, and the header text appears to have slidden up.

**Comment by drewmiley** [comment]
@Jason2605 Made a small change to the padding-bottom on small screen widths. This appears to fix whitespace issues on devices

**Comment by Jason2605** [comment]
@drewmiley Unfortunately these changes have caused an issue where you need to scroll to view the video on mobile devices. This shouldn't be the case. Instead in landscape mode the video should fill the screen (or on bigger devices a portion of the screen) and a user should never have to scroll to view the video.

Worth noting this is in regards to the "watch showreel" section.

**Comment by drewmiley** [comment]
This causes an issue on the client stories pages where the index area of a client story no longer has a straight line at the bottom.

**Comment by kmd-thomasBrace** [comment]
Fixed issue with whitespace on small devices without having the user to have to scroll down when in landscape

**Comment by onion2k** [comment]
Website is on SquareSpace now. This isn't needed any more.

**Pull request closed without merging**
